CIRCUITPY_WIFI_SSID = "your-ssid"
CIRCUITPY_WIFI_PASSWORD = "your-password"
broker_ip = "192.168.0.2"
broker_port = 1883
client_id = "Ground Office"
uname = "ground_office"
pass = "your-client-password"
client_topic = "signs/gf_sign"
unit_width = 64
unit_height = 64
bit_depth = 3
chain_height = 1
chain_width = 1
serpentine = "True"
rotation = 180
bedtime_hr = 00 - 23 only
bedtime_min = 00 - 59 only
wake_hr = 00 - 23 only
wake_min = 00 - 59 only
last_sleep_day = 0 
sleep_duration_seconds = 60
use_bedtime = "True"