# Signinator Board Configuration File
name = "Pi Pico W, Adafruit RGB + RTC for Raspberry Pi, HUB75 64x64 LED Matrix"

additional_dependencies = ["framebufferio","digitalio","rgbmatrix"]

display = '''
matrix = rgbmatrix.RGBMatrix(
   width = unit_width * fetch('chain_width'), 
   height = unit_height * fetch('chain_height') , 
   bit_depth = fetch('bit_depth'),
   rgb_pins = [board.GP2, board.GP3, board.GP4, board.GP5, board.GP8, board.GP9],
   addr_pins = [board.GP10, board.GP16, board.GP18, board.GP20, board.GP22],
   clock_pin = board.GP11, latch_pin = board.GP12, output_enable_pin = board.GP13,
   tile = fetch('chain_height'), serpentine = eval(fetch('serpentine')),
   doublebuffer = True)

display = framebufferio.FramebufferDisplay(matrix, rotation = fetch('rotation'), auto_refresh=False)
'''

# settings.toml config
[settings]
CIRCUITPY_WIFI_SSID = "your-ssid"
CIRCUITPY_WIFI_PASSWORD = "your-password"
broker_ip = "192.168.0.2"
broker_port = 1883
client_id = "Ground Office"
uname = "ground_office"
pass = "your-client-password"
client_topic = "signs/gf_sign"
unit_width = 64
unit_height = 64
bit_depth = 3
chain_height = 1
chain_width = 1
serpentine = "True"
rotation = 180
bedtime_hr = 0
bedtime_min = 0
wake_hr = 0
wake_min = 0
last_sleep_day = 0 
sleep_duration_seconds = 60
use_bedtime = "True"